import { ReactNode } from "react";
import Head from "next/head";
import { SidebarProvider } from "@features/Sidebar/context/sidebar.context";
import { Sidebar } from "@features/Sidebar/components/Sidebar";

type Props = {
  children: ReactNode;
};

export const MainLayout = (props: Props) => {
  const { children } = props;

  return (
    <>
      <Head>
        <title>Тёплые окна</title>
        <meta name="description" content="Generated by best dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-1">
        <SidebarProvider>
          <Sidebar />
        </SidebarProvider>
        <div className="bg-primary w-full overflow-hidden py-5 px-6 ">
          {children}
        </div>
      </main>
    </>
  );
};
